// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package rules

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	CreateRuleDestination(ctx context.Context, arg CreateRuleDestinationParams) (RuleDestination, error)
	DeleteRule(ctx context.Context, arg DeleteRuleParams) error
	DeleteRuleDestination(ctx context.Context, arg DeleteRuleDestinationParams) error
	GetRuleByID(ctx context.Context, arg GetRuleByIDParams) (Rule, error)
	GetRulesForEvent(ctx context.Context, arg GetRulesForEventParams) ([]Rule, error)
	ListNotificationChannelsForRule(ctx context.Context, ruleID uuid.UUID) ([]NotificationChannel, error)
	ListRuleDestinationChannelIDs(ctx context.Context, ruleID uuid.UUID) ([]uuid.UUID, error)
	ListRules(ctx context.Context, arg ListRulesParams) ([]Rule, error)
	UpdateRuleActive(ctx context.Context, arg UpdateRuleActiveParams) (Rule, error)
}

var _ Querier = (*Queries)(nil)
