// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package events

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	FetchNextEventForProcessing(ctx context.Context, lockedBy sql.NullString) (uuid.UUID, error)
	GetEventByID(ctx context.Context, id uuid.UUID) (Event, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertEventProcessingQueue(ctx context.Context, eventID uuid.UUID) (EventProcessingQueue, error)
	MarkEventProcessingDone(ctx context.Context, eventID uuid.UUID) error
	MarkEventProcessingFailed(ctx context.Context, arg MarkEventProcessingFailedParams) error
}

var _ Querier = (*Queries)(nil)
