// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package notificationchannels

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID          uuid.UUID    `json:"id"`
	TenantID    uuid.UUID    `json:"tenant_id"`
	RuleID      uuid.UUID    `json:"rule_id"`
	EventID     uuid.UUID    `json:"event_id"`
	TriggeredAt sql.NullTime `json:"triggered_at"`
	Notified    sql.NullBool `json:"notified"`
}

type AlertProcessingQueue struct {
	ID          uuid.UUID      `json:"id"`
	AlertID     uuid.UUID      `json:"alert_id"`
	Status      string         `json:"status"`
	LockedAt    sql.NullTime   `json:"locked_at"`
	LockedBy    sql.NullString `json:"locked_by"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	Error       sql.NullString `json:"error"`
}

type Event struct {
	ID         uuid.UUID       `json:"id"`
	TenantID   uuid.UUID       `json:"tenant_id"`
	WebhookID  uuid.UUID       `json:"webhook_id"`
	Source     string          `json:"source"`
	EventType  string          `json:"event_type"`
	Action     sql.NullString  `json:"action"`
	RawPayload json.RawMessage `json:"raw_payload"`
	DedupHash  sql.NullString  `json:"dedup_hash"`
	ReceivedAt sql.NullTime    `json:"received_at"`
}

type EventProcessingQueue struct {
	ID          int32          `json:"id"`
	EventID     uuid.UUID      `json:"event_id"`
	Status      string         `json:"status"`
	LockedAt    sql.NullTime   `json:"locked_at"`
	LockedBy    sql.NullString `json:"locked_by"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	Error       sql.NullString `json:"error"`
}

type NotificationChannel struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Config    json.RawMessage `json:"config"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Rule struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	EventType   string         `json:"event_type"`
	Sql         string         `json:"sql"`
	EvalType    string         `json:"eval_type"`
	AlertLevel  string         `json:"alert_level"`
	CreatedAt   time.Time      `json:"created_at"`
	Active      bool           `json:"active"`
}

type RuleDestination struct {
	RuleID    uuid.UUID `json:"rule_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

type Tenant struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Webhook struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	Secret    string          `json:"secret"`
	Source    string          `json:"source"`
	Events    json.RawMessage `json:"events"`
	CreatedAt sql.NullTime    `json:"created_at"`
}
