// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package notificationchannels

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error)
	GetNotificationChannelByID(ctx context.Context, id uuid.UUID) (NotificationChannel, error)
	GetNotificationChannelByTenantAndName(ctx context.Context, arg GetNotificationChannelByTenantAndNameParams) (NotificationChannel, error)
	ListNotificationChannels(ctx context.Context, tenantID uuid.UUID) ([]NotificationChannel, error)
}

var _ Querier = (*Queries)(nil)
