// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package alerts

import (
	"context"
)

type Querier interface {
	CreateAlert(ctx context.Context, arg CreateAlertParams) (CreateAlertRow, error)
}

var _ Querier = (*Queries)(nil)
