// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package webhooks

import (
	"context"
)

type Querier interface {
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error)
}

var _ Querier = (*Queries)(nil)
