// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Alert struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	RuleID      uuid.NullUUID   `json:"rule_id"`
	Event       json.RawMessage `json:"event"`
	TriggeredAt sql.NullTime    `json:"triggered_at"`
	Notified    sql.NullBool    `json:"notified"`
}

type NotificationChannel struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Type      string          `json:"type"`
	Config    json.RawMessage `json:"config"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Rule struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	Sql         string         `json:"sql"`
	EvalType    string         `json:"eval_type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type RuleNotification struct {
	RuleID    uuid.UUID `json:"rule_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

type Tenant struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Webhook struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	Secret    string          `json:"secret"`
	Source    string          `json:"source"`
	Events    json.RawMessage `json:"events"`
	CreatedAt sql.NullTime    `json:"created_at"`
}
