// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Alert struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	RuleID    uuid.UUID       `json:"rule_id"`
	Message   string          `json:"message"`
	Severity  string          `json:"severity"`
	Data      json.RawMessage `json:"data"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type NotificationChannel struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Config    json.RawMessage `json:"config"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Rule struct {
	ID                    uuid.UUID    `json:"id"`
	TenantID              uuid.UUID    `json:"tenant_id"`
	Name                  string       `json:"name"`
	Sql                   string       `json:"sql"`
	Severity              string       `json:"severity"`
	NotificationChannelID uuid.UUID    `json:"notification_channel_id"`
	Enabled               sql.NullBool `json:"enabled"`
	CreatedAt             sql.NullTime `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Webhook struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	Secret    string          `json:"secret"`
	Source    string          `json:"source"`
	Events    json.RawMessage `json:"events"`
	CreatedAt sql.NullTime    `json:"created_at"`
}
