// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (tenant_id, name, secret, source)
VALUES ($1, $2, $3, $4)
    RETURNING id, tenant_id, name, secret, source, created_at
`

type CreateWebhookParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Secret   string    `json:"secret"`
	Source   string    `json:"source"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.TenantID,
		arg.Name,
		arg.Secret,
		arg.Source,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Secret,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
