name: Hurl API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  hurl-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: sqlsec
          POSTGRES_PASSWORD: sqlsec
          POSTGRES_DB: sqlsec
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      SQLSEC_DB_DSN: postgres://sqlsec:sqlsec@localhost:5432/sqlsec?sslmode=disable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done

      - name: Install Hurl
        run: |
          HURL_VERSION=4.3.0
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/${HURL_VERSION}/hurl_${HURL_VERSION}_amd64.deb
          sudo dpkg -i hurl_${HURL_VERSION}_amd64.deb

      - name: Apply schema
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          psql -h localhost -U sqlsec -d sqlsec -f schema.sql
        env:
          PGPASSWORD: sqlsec

      - name: Build sqlsec
        run: make build

      - name: Start sqlsec server
        run: ./bin/sqlsec serve &
        env:
          SQLSEC_DB_DSN: ${{ env.SQLSEC_DB_DSN }}
        shell: bash

      - name: Wait for sqlsec to be ready
        run: |
          for i in {1..10}; do
            curl -sf http://localhost:8080/health && exit 0
            sleep 2
          done
          echo "sqlsec did not start in time" && exit 1

      - name: Run Hurl tests
        run: make test-hurl
