name: Unit Tests

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Install DuckDB shared library
        run: |
          curl -L https://github.com/duckdb/duckdb/releases/download/v1.3.2/libduckdb-linux-amd64.zip -o libduckdb.zip
          unzip libduckdb.zip
          sudo cp libduckdb.so /usr/lib/
      - name: Build
        run: make build
      - name: Run unit tests
        run: LD_LIBRARY_PATH=/usr/lib make test
